apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rms

# Development configuration with functional PostGIS and Redis images
# These files are excluded from Azure security scanning

resources:
  - namespace.yaml
  - secret-sample.yaml
  - postgres.yaml
  - redis.yaml
  - deployment.yaml
  - ingress.yaml

images:
  - name: rms-demo
    newName: rms-demo
    newTag: local

labels:
  - includeSelectors: true
    pairs:
      app: rms-demo
      version: v1.1.0-dev
      environment: development
