---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: rms
  labels:
    app: postgres
    tier: database
    environment: development
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      tier: database
  template:
    metadata:
      labels:
        app: postgres
        tier: database
    spec:
      containers:
        - name: postgres
          image: postgis/postgis:15-3.4-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: rmsdemodb
            - name: POSTGRES_USER
              value: rmsuser
            - name: POSTGRES_PASSWORD
              value: defaultpassword
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: rms
  labels:
    app: postgres
    tier: database
spec:
  selector:
    app: postgres
    tier: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
