version: 2
updates:
  # Enable version updates for .NET dependencies
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "msftsean"
    assignees:
      - "msftsean"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps"
      include: "scope"
    # Security updates get higher priority
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Group minor and patch updates
    groups:
      microsoft-packages:
        patterns:
          - "Microsoft.*"
        update-types:
          - "minor"
          - "patch"

  # Docker base image updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    reviewers:
      - "msftsean"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "docker"

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    reviewers:
      - "msftsean"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "actions"

  # NPM dependencies (if frontend exists)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "thursday"  
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "msftsean"
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "npm"
    # Ignore dev dependencies for automatic updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
        
  # Terraform updates (if infrastructure exists)
  - package-ecosystem: "terraform"
    directory: "/infrastructure"
    schedule:
      interval: "monthly"
      time: "09:00"
    reviewers:
      - "msftsean"
    labels:
      - "dependencies"
      - "infrastructure"
    commit-message:
      prefix: "terraform"
