---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rms-demo
  namespace: rms
  labels:
    app: rms-demo
    tier: backend
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rms-demo
      tier: backend
  template:
    metadata:
      labels:
        app: rms-demo
        tier: backend
    spec:
      containers:
        - name: api
          image: rms-demo:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: rms-demo-secrets
                  key: connectionString
---
apiVersion: v1
kind: Service
metadata:
  name: rms-demo
  namespace: rms
  labels:
    app: rms-demo
    tier: backend
spec:
  selector:
    app: rms-demo
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
