name: 🔒 Security Vulnerability
description: Report a security vulnerability (private)
title: "[SECURITY]: "
labels: ["security", "vulnerability"]
assignees:
  - msftsean
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT**: Please do not report security vulnerabilities in public issues.
        
        If this is a security vulnerability, please report it privately through:
        - GitHub Security Advisories (preferred)
        - Email to security@example.com
        
        For non-security issues, please use the other issue templates.

  - type: textarea
    id: vulnerability-description
    attributes:
      label: Vulnerability Description
      description: Provide a clear description of the vulnerability
      placeholder: Describe the security issue...
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this vulnerability?
      options:
        - Critical
        - High
        - Medium
        - Low
      default: 0

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can the vulnerability be reproduced?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See vulnerability...

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: What is the potential impact of this vulnerability?
      placeholder: This vulnerability could allow...

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: If you have suggestions for how to fix this issue, please describe them here.

  - type: checkboxes
    id: disclosure
    attributes:
      label: Responsible Disclosure
      description: Please confirm your commitment to responsible disclosure
      options:
        - label: I will follow responsible disclosure practices
          required: true
        - label: I will not publicly disclose this issue until it's resolved
          required: true
