apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rms
resources:
  - ../../k8s
patches:
  - target:
      kind: Ingress
      name: rms-demo
    patch: |-
      - op: replace
        path: /spec/ingressClassName
        value: nginx
