apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Azure-specific deployment with Microsoft-approved images only
# This overlay contains zero external registry references

resources:
- azure-deployment.yaml
- ../../namespace.yaml
- ../../secret-sample.yaml
- ../../ingress.yaml

# Add Azure-specific labels
commonLabels:
  environment: azure
  compliance: microsoft-approved-images

# Azure-specific patches for production
patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: Secret
  metadata:
    name: postgres-secret
    namespace: rms
  stringData:
    # In production, use Azure Key Vault
    password: "REPLACE_WITH_AZURE_KEY_VAULT_REFERENCE"
