apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Azure-specific deployment with Microsoft-approved images only
resources:
- azure-deployment.yaml
- ../../namespace.yaml
- ../../secret-sample.yaml

# Add Azure-specific labels
commonLabels:
  environment: azure
  compliance: microsoft-approved-images

# Azure-specific configuration
patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: Secret
  metadata:
    name: postgres-secret
    namespace: rms
  data:
    # These should be set via Azure Key Vault in production
    password: ""
