name: Deploy to AKS (placeholder)

on:
	workflow_dispatch:

jobs:
	noop:
		runs-on: ubuntu-latest
		steps:
			- name: Checkout
				uses: actions/checkout@v4
			- name: Placeholder
				run: echo "AKS deploy workflow placeholder - no-op"

